### PR TITLE
fix: Global min Self Delegation

### LINKED ISSUE #113: Add a global Minimum self delegation
## Summary

Add a global minimum self delegation parameter, similar to the minimum commission rate.

## Problem Definition

This isn't a big restriction, as limited validator slots already _effectively_ has this requirement. However this increases the costs to spam the number of validators. The number of validators active in the last $UNBONDING_PERIOD can have unfortunate impacts on efficiency when an app-chain's module has other amplification factors on the load caused by validators.

The base SDK has some amplification factor here, (state storage, historical signing info windows), but on brief skim nothing concerning, hence why it likely wasn't thought about before.

## Proposal

Add a global minimum self delegation parameter to the codebase. For Osmosis, I suggest making it something like 100 osmo, which makes attacks that concern me very infeasible.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

### PR DESCRIPTION
**Pull request by AlpinYukseloglu**
Closes: #113 

## What is the purpose of the change

Our current implementation of Superfluid Staking exposes the chain to a specific vulnerability relating to the validator creation process. This PR adds the necessary guardrails to make sure that an attacker cannot halt the chain by generating an arbitrary number of empty validators. 

This was not an issue prior to Superfluid Staking because the full validator set was not used in the ante anywhere, but our specific implementation of Superfluid introduced a linear-time search of the validator set at epoch end that made the issue fixed in this PR a vulnerability.

### CODE REVIEW

File: x/staking/legacy/v040/migrate.go [hunk 1]
```diff
@@ -130,6 +130,7 @@ func Migrate(stakingState v038staking.GenesisState) *GenesisState {
 			HistoricalEntries: uint32(stakingState.Params.HistoricalEntries),
 			BondDenom:         stakingState.Params.BondDenom,
 			MinCommissionRate: v040staking.DefaultMinCommissionRate,
+			// MinSelfDelegation: v040staking.DefaultMinSelfDelegation,
```
Comment (mattverse) [inline x/staking/legacy/v040/migrate.go]: Is there a reason this was added? Just curious

**Review by mattverse — CHANGES_REQUESTED** [review]
Would it be able to add tests for this change?(genesis_test, params_test in sim etc)

Also, how does this param enforce validators to have `min_self_delegation`?

File: x/staking/legacy/v040/migrate.go (hunk 1 above)
Comment (AlpinYukseloglu) [reply x/staking/legacy/v040/migrate.go]: Ah looks like I forgot to remove this comment - I had mistakenly tried to add support for the new parameter to the migration file based on previous commits for other parameters that were added and realized afterwards that that was not necessary/correct. Removed in my most recent commit!

**Comment by ValarDragon** [comment]
Migration code LGTM! Just realized theres still one missing change, adding the new parameter to `params.go`, and the ExportGenesis and ImportGenesis code

File: docs/core/proto-docs.md [hunk 2]
```diff
@@ -6505,6 +6505,7 @@ Params defines the parameters for the staking module.
 | `historical_entries` | [uint32](#uint32) |  | historical_entries is the number of historical entries to persist. |
 | `bond_denom` | [string](#string) |  | bond_denom defines the bondable coin denomination. |
 | `min_commission_rate` | [string](#string) |  | min_commission_rate is the chain-wide minimum commission rate that a validator can charge their delegators |
+| `min_self_delegation` | [string](#string) |  | min_commission_rate is the chain-wide minimum commission rate that a validator can charge their delegators |
```
Comment (ValarDragon) [inline docs/core/proto-docs.md:6508]: Need to update the description for this one

Comment (ValarDragon) [inline docs/core/proto-docs.md]:
```suggestion
| `min_self_delegation` | [string](#string) |  | min_self_delegation is the chain-wide minimum self delegation a validator can have |
```

**Review by ValarDragon — APPROVED** [review]

**Comment by ValarDragon** [comment]
@AlpinYukseloglu you have to update the GetParams queries for the new field in the param struct before merge.

To test locally, inside of `x/staking` do `go test ./...`, the query tests should fail.

**Comment by ValarDragon** [comment]
https://github.com/osmosis-labs/cosmos-sdk/runs/5564114018?check_suite_focus=true

still failing

**Comment by AlpinYukseloglu** [comment]
> https://github.com/osmosis-labs/cosmos-sdk/runs/5564114018?check_suite_focus=true
> 
> still failing

Interesting... local tests seem to be passing (`go test ./...` in `x/staking` and then also in its parent folders) except for when I do it in the highest folder (`cosmos-sdk`), in which case the handful of tests that fail are all ledger-related ("support for ledger devices is not available in this executable"). Am I testing incorrectly @ValarDragon?

**Comment by mattverse** [comment]
FYI: The Rosetta test was broken in the main sdk branch as well

**Review by mattverse — COMMENTED** [review]
Actually, it seems that something in this PR does seem to break the rosetta-test that needs further investigation on fixes. Also, by a brief look, it seems that the "build" action might be failing due to changes in `go.sum`, can you revert go.sum into the original state?

**Comment by ValarDragon** [comment]
TODO: Ask in cosmos SDK discord how rosetta tests work / how to debug this failure.

If theres a genesis file somewhere for Rosetta, we did break it / would have to update it for this PR

**Comment by alexanderbez** [comment]
Frojdi told me to look at this function:

```
// ToRosetta attempts to converting an error into a rosetta
// error, if the error cannot be converted it will be parsed as unknown
func ToRosetta(err error) *types.Error {
    if err == nil {
        return nil
    }
    // if it's null or not known
    rosErr, ok := err.(*Error)
    if !ok {
        return ToRosetta(WrapError(ErrUnknown, err.Error()))
    }
    return rosErr.rosErr
}
```

I think we need to log `err` in the beginning of the function to get better insight into what's going on.

File: x/staking/keeper/migrations.go [hunk 3]
```diff
@@ -19,3 +20,8 @@ func NewMigrator(keeper Keeper) Migrator {
 func (m Migrator) Migrate1to2(ctx sdk.Context) error {
 	return v043.MigrateStore(ctx, m.keeper.storeKey)
 }
+
+// Migrate1to2 migrates from version 1 to 2.
```
Comment (alexanderbez) [inline x/staking/keeper/migrations.go]:
```suggestion
// Migrate1to2 migrates from version 2 to 3.
```

File: x/staking/keeper/msg_server.go [hunk 4]
```diff
@@ -56,6 +56,11 @@ func (k msgServer) CreateValidator(goCtx context.Context, msg *types.MsgCreateVa
 		)
 	}
 
+	//Uses GT instead of GTE for consistency with other MinSelfDelegation checks
+	if msg.MinSelfDelegation.GT(msg.Value.Amount) {
```
Comment (alexanderbez) [inline x/staking/keeper/msg_server.go]: Wouldn't `msg.Value.Amount.LT(msg.MinSelfDelegation)` be easier to read and understand?

File: x/staking/legacy/v046/store.go [hunk 5]
```diff
@@ -0,0 +1,24 @@
+package v046
+
+//package v046
```
Comment (alexanderbez) [inline x/staking/legacy/v046/store.go]:
```suggestion
```

File: x/staking/legacy/v046/store.go [hunk 6]
```diff
@@ -0,0 +1,24 @@
...
+// - Setting the MinCommissionRate param in the paramstore
+func MigrateStore(ctx sdk.Context, paramstore paramtypes.Subspace) error {
+	migrateParamsStore(ctx, paramstore)
+
+	return nil
+}
+
+func migrateParamsStore(ctx sdk.Context, paramstore paramtypes.Subspace) {
+	paramstore.WithKeyTable(types.ParamKeyTable())
+	paramstore.Set(ctx, types.KeyMinSelfDelegation, types.DefaultMinSelfDelegation)
```
Comment (alexanderbez) [inline x/staking/legacy/v046/store.go]: We should probably redefine `types.DefaultMinSelfDelegation` here instead of importing `staking/types`, since that value can change at any moment.

File: x/staking/legacy/v046/store_test.go [hunk 7]
```diff
@@ -0,0 +1,34 @@
+package v046_test
+
+//package v046_test
```
Comment (alexanderbez) [inline x/staking/legacy/v046/store_test.go]:
```suggestion
```

File: x/staking/keeper/msg_server.go [hunk 8]
```diff
@@ -99,6 +104,13 @@ func (k msgServer) CreateValidator(goCtx context.Context, msg *types.MsgCreateVa
 
 	validator.MinSelfDelegation = msg.MinSelfDelegation
 
+	globalMinSelfDelegation := k.MinSelfDelegation(ctx)
+
+	//Minimum validator self delegation must be greater than or equal to global minimum
+	if globalMinSelfDelegation.GT(validator.MinSelfDelegation) {
```
Comment (alexanderbez) [inline x/staking/keeper/msg_server.go]: Same, I think `validator.MinSelfDelegation.LT(globalMinSelfDelegation)` would be easier to understand, no?

File: x/staking/keeper/msg_server.go (hunk 4 above)
Comment (AlpinYukseloglu) [reply x/staking/keeper/msg_server.go]: Agreed - changed in recent commit!

File: x/staking/keeper/msg_server.go (hunk 8 above)
Comment (AlpinYukseloglu) [reply x/staking/keeper/msg_server.go]: Agreed - changed in recent commit!

File: x/staking/legacy/v046/store.go (hunk 6 above)
Comment (AlpinYukseloglu) [reply x/staking/legacy/v046/store.go]: This is a really good point. Added in recent commit.

File: x/staking/keeper/msg_server.go [hunk 9]
```diff
@@ -99,6 +103,13 @@ func (k msgServer) CreateValidator(goCtx context.Context, msg *types.MsgCreateVa
 
 	validator.MinSelfDelegation = msg.MinSelfDelegation
 
+	globalMinSelfDelegation := k.MinSelfDelegation(ctx)
+
+	//Minimum validator self delegation must be greater than or equal to global minimum
```
Comment (alexanderbez) [inline x/staking/keeper/msg_server.go]:
```suggestion
	// minimum validator self delegation must be greater than or equal to global minimum
```

File: x/staking/keeper/msg_server.go [hunk 10]
```diff
@@ -163,6 +174,13 @@ func (k msgServer) EditValidator(goCtx context.Context, msg *types.MsgEditValida
 		validator.Commission = commission
 	}
 
+	globalMinSelfDelegation := k.MinSelfDelegation(ctx)
+
+	//Minimum validator self delegation must be greater than or equal to global minimum
```
Comment (alexanderbez) [inline x/staking/keeper/msg_server.go]:
```suggestion
	// minimum validator self delegation must be greater than or equal to global minimum
```

File: x/staking/keeper/msg_server.go [hunk 11]
```diff
@@ -163,6 +174,13 @@ func (k msgServer) EditValidator(goCtx context.Context, msg *types.MsgEditValida
...
+	if globalMinSelfDelegation.GT(validator.MinSelfDelegation) {
```
Comment (alexanderbez) [inline x/staking/keeper/msg_server.go]:
```suggestion
	if validator.MinSelfDelegation.LT(globalMinSelfDelegation) {
```

**Review by alexanderbez — APPROVED** [review]
🚀 🚀 🚀
